# -*- coding: utf-8 -*-
{
    'name': "Mawa Website",

    'summary': """""",

    'description': """

    """,

    'author': "Muhammad Hasnain",
    'sequence': -200,

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/16.0/odoo/addons/base/data/ir_module_category_data.xml
    # for the full list
    'category': 'application',
    'version': '1.0.0',

    # any module necessary for this one to work correctly
    'depends': ['base', 'website'],
    'assets': {
        'web.assets_frontend': [
            '/mawa_website/static/src/css/main.css',
            '/mawa_website/static/src/css/util.css',
            '/mawa_website/static/src/fonts/font-awesome-4.7.0/css/font-awesome.css',
            '/mawa_website/static/src/fonts/font-awesome-4.7.0/css/font-awesome.min.css',
            '/mawa_website/static/src/fonts/font-awesome-4.7.0/scss/_animated.scss',
            '/mawa_website/static/src/fonts/font-awesome-4.7.0/scss/_bordered-pulled.scss',
            '/mawa_website/static/src/fonts/font-awesome-4.7.0/scss/_core.scss',
            '/mawa_website/static/src/fonts/font-awesome-4.7.0/scss/_fixed-width.scss',
            '/mawa_website/static/src/fonts/font-awesome-4.7.0/scss/_icons.scss',
            '/mawa_website/static/src/fonts/font-awesome-4.7.0/scss/_larger.scss',
            '/mawa_website/static/src/fonts/font-awesome-4.7.0/scss/_list.scss',
            '/mawa_website/static/src/fonts/font-awesome-4.7.0/scss/_mixins.scss',
            '/mawa_website/static/src/fonts/font-awesome-4.7.0/scss/_path.scss',
            '/mawa_website/static/src/fonts/font-awesome-4.7.0/scss/_rotated-flipped.scss',
            '/mawa_website/static/src/fonts/font-awesome-4.7.0/scss/_screen-reader.scss',
            '/mawa_website/static/src/fonts/font-awesome-4.7.0/scss/_stacked.scss',
            '/mawa_website/static/src/fonts/font-awesome-4.7.0/scss/_variables.scss',
            '/mawa_website/static/src/fonts/iconic/css/material-design-iconic-font.css',
            '/mawa_website/static/src/fonts/iconic/css/material-design-iconic-font.min.css',
            '/mawa_website/static/src/fonts/linearicons-v1.0.0/icon-font.min.css',
            '/mawa_website/static/src/js/main.js',
            '/mawa_website/static/src/js/map-custom.js',
            '/mawa_website/static/src/js/slick-custom.js',
            '/mawa_website/static/src/vendor/animate/animate.css',
            '/mawa_website/static/src/vendor/animsition/css/animsition.css',
            '/mawa_website/static/src/vendor/animsition/css/animsition.min.css',
            '/mawa_website/static/src/vendor/animsition/js/animsition.js',
            '/mawa_website/static/src/vendor/animsition/js/animsition.min.js',
            '/mawa_website/static/src/vendor/bootstrap/css/bootstrap.css',
            '/mawa_website/static/src/vendor/bootstrap/css/bootstrap.css.map',
            '/mawa_website/static/src/vendor/bootstrap/css/bootstrap.min.css',
            '/mawa_website/static/src/vendor/bootstrap/css/bootstrap.min.css.map',
            '/mawa_website/static/src/vendor/bootstrap/css/bootstrap-grid.css',
            '/mawa_website/static/src/vendor/bootstrap/css/bootstrap-grid.css.map',
            '/mawa_website/static/src/vendor/bootstrap/css/bootstrap-grid.min.css',
            '/mawa_website/static/src/vendor/bootstrap/css/bootstrap-grid.min.css.map',
            '/mawa_website/static/src/vendor/bootstrap/css/bootstrap-reboot.css',
            '/mawa_website/static/src/vendor/bootstrap/css/bootstrap-reboot.css.map',
            '/mawa_website/static/src/vendor/bootstrap/css/bootstrap-reboot.min.css',
            '/mawa_website/static/src/vendor/bootstrap/css/bootstrap-reboot.min.css.map',
            '/mawa_website/static/src/vendor/bootstrap/css/bootstrap-reboot.rtl.css',
            '/mawa_website/static/src/vendor/bootstrap/css/bootstrap-reboot.rtl.css.map',
            '/mawa_website/static/src/vendor/bootstrap/css/bootstrap-reboot.rtl.min.css',
            '/mawa_website/static/src/vendor/bootstrap/js/bootstrap.js',
            '/mawa_website/static/src/vendor/bootstrap/js/bootstrap.min.js',
            '/mawa_website/static/src/vendor/bootstrap/js/popper.js',
            '/mawa_website/static/src/vendor/bootstrap/js/popper.min.js',
            '/mawa_website/static/src/vendor/bootstrap/js/tooltip.js',
            '/mawa_website/static/src/vendor/countdowntime/countdowntime.js',
            '/mawa_website/static/src/vendor/css-hamburgers/hamburgers.css',
            '/mawa_website/static/src/vendor/css-hamburgers/hamburgers.min.css',
            '/mawa_website/static/src/vendor/daterangepicker/daterangepicker.css',
            '/mawa_website/static/src/vendor/daterangepicker/daterangepicker.js',
            '/mawa_website/static/src/vendor/daterangepicker/moment.js',
            '/mawa_website/static/src/vendor/daterangepicker/moment.min.js',
            '/mawa_website/static/src/vendor/isotope/isotope.pkgd.min.js',
            '/mawa_website/static/src/vendor/jquery/jquery-3.2.1.min.js',
            '/mawa_website/static/src/vendor/jqueryui/external/jquery/jquery.js',
            '/mawa_website/static/src/vendor/jqueryui/jquery-ui.css',
            '/mawa_website/static/src/vendor/jqueryui/jquery-ui.js',
            '/mawa_website/static/src/vendor/jqueryui/jquery-ui.min.css',
            '/mawa_website/static/src/vendor/jqueryui/jquery-ui.min.js',
            '/mawa_website/static/src/vendor/jqueryui/jquery-ui.structure.css',
            '/mawa_website/static/src/vendor/jqueryui/jquery-ui.structure.min.css',
            '/mawa_website/static/src/vendor/jqueryui/jquery-ui.theme.css',
            '/mawa_website/static/src/vendor/jqueryui/jquery-ui.theme.min.css',
            '/mawa_website/static/src/vendor/lightbox2/css/lightbox.css',
            '/mawa_website/static/src/vendor/lightbox2/css/lightbox.min.css',
            '/mawa_website/static/src/vendor/lightbox2/js/lightbox.js',
            '/mawa_website/static/src/vendor/lightbox2/js/lightbox.min.js',
            '/mawa_website/static/src/vendor/lightbox2/js/lightbox.min.map',
            '/mawa_website/static/src/vendor/lightbox2/js/lightbox-plus-jquery.js',
            '/mawa_website/static/src/vendor/lightbox2/js/lightbox-plus-jquery.min.js',
            '/mawa_website/static/src/vendor/lightbox2/js/lightbox-plus-jquery.min.map',
            '/mawa_website/static/src/vendor/MagnificPopup/jquery.magnific-popup.js',
            '/mawa_website/static/src/vendor/MagnificPopup/jquery.magnific-popup.min.js',
            '/mawa_website/static/src/vendor/MagnificPopup/magnific-popup.css',
            '/mawa_website/static/src/vendor/parallax100/parallax100.js',
            '/mawa_website/static/src/vendor/perfect-scrollbar/perfect-scrollbar.css',
            '/mawa_website/static/src/vendor/perfect-scrollbar/perfect-scrollbar.min.js',
            '/mawa_website/static/src/vendor/select2/select2.css',
            '/mawa_website/static/src/vendor/select2/select2.js',
            '/mawa_website/static/src/vendor/select2/select2.min.css',
            '/mawa_website/static/src/vendor/select2/select2.min.js',
            '/mawa_website/static/src/vendor/slick/slick.css',
            '/mawa_website/static/src/vendor/slick/slick.js',
            '/mawa_website/static/src/vendor/slick/slick.less',
            '/mawa_website/static/src/vendor/slick/slick.min.js',
            '/mawa_website/static/src/vendor/slick/slick.scss',
            '/mawa_website/static/src/vendor/slick/slick-theme.css',
            '/mawa_website/static/src/vendor/slick/slick-theme.less',
            '/mawa_website/static/src/vendor/slick/slick-theme.scss',
            '/mawa_website/static/src/vendor/sweetalert/sweetalert.min.js',
        ],
    },

    # always loaded
    'data': [
        'security/ir.model.access.csv',
        'views/header.xml',
        'views/homepage.xml',
        'views/about.xml',
        'views/contact.xml',
        'views/footer.xml',
    ],
    # only loaded in demonstration mode
    'demo': [
    ],
    'qweb': [
    ],
    'application': True,
}
